# Veritas Documents - Production Secrets Setup
# Run this to set up only the essential secrets

Write-Host "Setting up production secrets..." -ForegroundColor Green

# Essential secrets (you need real values for these)
$secrets = @{
    "STRIPE_SECRET_KEY" = "sk_live_YOUR_REAL_STRIPE_SECRET_KEY"
    "STRIPE_WEBHOOK_SECRET" = "whsec_YOUR_REAL_STRIPE_WEBHOOK_SECRET"
    "IPFS_API_KEY" = "YOUR_REAL_CLOUDFLARE_IPFS_API_KEY"
    "ETHEREUM_PRIVATE_KEY" = "0xYOUR_REAL_ETHEREUM_PRIVATE_KEY"
    "VERITAS_CONTRACT_ADDRESS" = "0xYOUR_REAL_CONTRACT_ADDRESS"
}

# Auto-generated secrets (these are already set)
Write-Host "These secrets are already configured:" -ForegroundColor Yellow
Write-Host "- MAATARA_CHAIN_PRIVATE_KEY (generated by CLI)"
Write-Host "- ADMIN_SECRET_KEY (generated by CLI)"
Write-Host ""
Write-Host "You need to get real values for:" -ForegroundColor Cyan
foreach ($key in $secrets.Keys) {
    Write-Host "- $key"
}
Write-Host ""
Write-Host "Get them from:" -ForegroundColor White
Write-Host "- Stripe: https://dashboard.stripe.com/apikeys"
Write-Host "- Cloudflare IPFS: https://dash.cloudflare.com/profile/api-tokens"
Write-Host "- Ethereum: Your wallet (MetaMask, etc.)"
Write-Host ""
Write-Host "Then run: wrangler secret put SECRET_NAME --env production" -ForegroundColor Green
