name = "veritas-docs"
main = "src/index.ts"
compatibility_date = "2024-01-01"

[env.production.vars]
ENVIRONMENT = "production"
MAATARA_API_BASE = "https://maatara-core-worker.rme-6e5.workers.dev"
ETHEREUM_RPC_URL = "https://cloudflare-eth.com/v1/mainnet"
IPFS_GATEWAY_URL = "https://cloudflare-ipfs.com"

[env.staging.vars]
ENVIRONMENT = "staging"

[[env.production.kv_namespaces]]
binding = "VERITAS_KV"
id = "9f0ea31309cd44cab7bfe3569e16aa45"

[[env.staging.kv_namespaces]]
binding = "VERITAS_KV"
id = "your-staging-kv-namespace-id"

[vars]
ENVIRONMENT = "development"
MAATARA_API_BASE = "https://maatara-core-worker.rme-6e5.workers.dev"
# Cloudflare Web3 Gateway URLs
ETHEREUM_RPC_URL = "https://cloudflare-eth.com/v1/mainnet"
IPFS_GATEWAY_URL = "https://cloudflare-ipfs.com"

[[kv_namespaces]]
binding = "VERITAS_KV"
id = "77a8b18c45f341b7aa1b91de1dc8a55e"
preview_id = "f280a31ef23b4d7cb29d5ac314457674"

# Add your secrets using: wrangler secret put SECRET_NAME
# STRIPE_SECRET_KEY
# STRIPE_WEBHOOK_SECRET
# MAATARA_CHAIN_PRIVATE_KEY
# IPFS_API_KEY
# ADMIN_SECRET_KEY
# Web3 Integration Secrets:
# VERITAS_CONTRACT_ADDRESS
# ETHEREUM_PRIVATE_KEY
# PINATA_API_KEY
# PINATA_SECRET_KEY