name = "veritas-docs"
main = "src/index.ts"
compatibility_date = "2024-01-01"

# Configure esbuild to load markdown files as text
[[rules]]
type = "Text"
globs = ["**/*.md"]
fallthrough = true

# Production configuration (default)
[vars]
ENVIRONMENT = "production"
MAATARA_API_BASE = "https://maatara-core-worker.rme-6e5.workers.dev"
ETHEREUM_RPC_URL = "https://cloudflare-eth.com/v1/mainnet"
IPFS_GATEWAY_URL = "https://cloudflare-ipfs.com"

[[kv_namespaces]]
binding = "VERITAS_KV"
id = "9f0ea31309cd44cab7bfe3569e16aa45"

[[r2_buckets]]
binding = "VDC_STORAGE"
bucket_name = "veritas-docs-production-storage"


# Add your secrets using: wrangler secret put SECRET_NAME
# STRIPE_SECRET_KEY
# STRIPE_WEBHOOK_SECRET
# MAATARA_CHAIN_PRIVATE_KEY
# IPFS_API_KEY
# ADMIN_SECRET_KEY
# Web3 Integration Secrets:
# VERITAS_CONTRACT_ADDRESS
# ETHEREUM_PRIVATE_KEY
# PINATA_API_KEY
# PINATA_SECRET_KEY