name = "veritas-docs"
main = "src/index.ts"
compatibility_date = "2024-01-01"

[env.production.vars]
ENVIRONMENT = "production"

[env.staging.vars]
ENVIRONMENT = "staging"

[[env.production.kv_namespaces]]
binding = "VERITAS_KV"
id = "your-production-kv-namespace-id"

[[env.staging.kv_namespaces]]
binding = "VERITAS_KV"
id = "your-staging-kv-namespace-id"

[vars]
ENVIRONMENT = "development"
MAATARA_API_BASE = "https://maatara-core-worker.rme-6e5.workers.dev"

# Add your secrets using: wrangler secret put SECRET_NAME
# STRIPE_SECRET_KEY
# STRIPE_WEBHOOK_SECRET
# MAATARA_CHAIN_PRIVATE_KEY
# IPFS_API_KEY
# ADMIN_SECRET_KEY